import { IProduct } from 'src/types/IProduct';

export const PRODUCTS_DATA: IProduct[] = [
  {
    id: 1,
    title: 'iPhone 9',
    price: 549,
    image: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
    rate: 4.8,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['urgently', 'bargain'],
  },
  {
    id: 2,
    title: 'iPhone X',
    price: 899,
    image: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['urgently'],
  },
  {
    id: 3,
    title: 'Samsung Universe 9',
    price: 1249,
    image: 'https://i.dummyjson.com/data/products/3/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: [],
  },
  {
    id: 4,
    title: 'OPPOF19',
    price: 280,
    image: 'https://i.dummyjson.com/data/products/4/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['bargain'],
  },
  {
    id: 5,
    title: 'Huawei P30',
    price: 499,
    image: 'https://i.dummyjson.com/data/products/5/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: [],
  },
  {
    id: 6,
    title: 'MacBook Pro',
    price: 1749,
    image: 'https://i.dummyjson.com/data/products/6/thumbnail.png',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['bargain'],
  },
  {
    id: 7,
    title: 'Samsung Galaxy Book',
    price: 1499,
    image: 'https://i.dummyjson.com/data/products/7/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['urgently', 'bargain'],
  },
  {
    id: 8,
    title: 'Microsoft Surface Laptop 4',
    price: 1499,
    image: 'https://i.dummyjson.com/data/products/8/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: [],
  },
  {
    id: 9,
    title: 'Infinix INBOOK',
    price: 1099,
    image: 'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['urgently', 'bargain'],
  },
  {
    id: 10,
    title: 'HP Pavilion 15-DK1056WM',
    price: 1099,
    image: 'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['bargain'],
  },
  {
    id: 11,
    title: 'perfume Oil',
    price: 13,
    image: 'https://i.dummyjson.com/data/products/11/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['bargain'],
  },
  {
    id: 12,
    title: 'Brown Perfume',
    price: 40,
    image: 'https://i.dummyjson.com/data/products/12/thumbnail.jpg',
    rate: 4.4,
    date: '12-12-2012',
    category: 'smartphones',
    condition: 'New',
    tags: ['urgently', 'bargain'],
  },
];
